
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/00_utils_nb.ipynb
import pandas as pd
import numpy as np
from fastai.text.all import *
from fastai.callback import *
from rdkit.Chem import MolFromSmiles, MolToSmiles
from GenerativeCallback import GenerativeCallback

ValidityBenchmark = ValueMetric(GenerativeCallback()._validity, 'validity')
UniquenessBenchmark = ValueMetric(GenerativeCallback()._uniqueness, 'uniqueness')
NoveltyBenchmark = ValueMetric(GenerativeCallback()._novelty, 'novelty')